version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: justin_portfolio_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - 'redis'

volumes:
  redis:
  postgres:
