default: &default
  adapter: postgresql
  encoding: unicode
  username:

  password:
  host: localhost

development:
  <<: *default
  database: 'justin_portfolio_development'

test:
  <<: *default

staging:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRESQL_HOST'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  pool: 5
  database: <%= ENV['POSTGRESQL_DB'] %>

production:
  <<: *default